version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.4.2
  jq: circleci/jq@2.2.0

jobs:
  build:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          command: mkdir ~/project/artifacts
      - run:
          command: mv output.pdf ~/project/artifacts/output.pdf
      - store_artifacts:
          path: ~/project/artifacts
      - jq/install
      - run:
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            --header "Circle-Token: $CIRCLE_TOKEN")
            artifact0=$(echo $artifacts | jq '.items[0].url')
            echo "export ARTIFACT0=$artifact0" >> $BASH_ENV 
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Book Artifacts <${ARTIFACT0}>"
                  }
                }
              ]
            }


workflows:
  ci:
    jobs:
      - build:
          context: slack

